[package]
name = "fastx"
version = "0.1.0"
authors = ["Erik Clarke <erikclarke@fastmail.com>"]

[dependencies]
regex="*"
itertools="*"

[dependencies.nom]
version="3.0"
features=["regexp_macros", "regexp"]

[dev-dependencies]
bio="0.13"